// Module included in the following assemblies:
//
// * installing/installing_aws/installing-aws-localzone.adoc

:_content-type: PROCEDURE
[id="installation-creating-aws-subnet-localzone_{context}"]
= Creating a subnet that uses AWS Local Zones

You must create a subnet in Amazon Web Services (AWS) that uses local zones for your {product-title}
cluster to use.

You can use the provided CloudFormation template and a custom parameter file to create a stack of AWS resources that represent the subnet.

[NOTE]
====
If you do not use the provided CloudFormation template to create your AWS
infrastructure, you must review the provided information and manually create
the infrastructure. If your cluster does not initialize correctly, you might
have to contact Red Hat support with your installation logs.
====

.Prerequisites

* You configured an AWS account.
* You added your AWS keys and region to your local AWS profile by running `aws configure`.
* You opted in your AWS account to the local zone that hosts your VPC.
* You generated the Ignition config files for your cluster.

.Procedure

. Create a JSON file that contains the parameter values that the template
requires:
+
[source,json]
----
[
  {
    "ParameterKey": "ClusterName", <1>
    "ParameterValue": "mycluster" <2>
  },
  {
    "ParameterKey": "VpcId", <3>
    "ParameterValue": "vpc-<random_string>" <4>
  },
  {
    "ParameterKey": "PublicRouteTableId", <5>
    "ParameterValue": "<vpc_rtb_pub>" <6>
  },
  {
    "ParameterKey": "LocalZoneName", <7>
    "ParameterValue": "<cluster_region_name>-<location_identifier>-<zone_identifier>" <8>
  },
  {
    "ParameterKey": "LocalZoneNameShort", <9>
    "ParameterValue": "<lz_zone_shortname>" <10>
  },
  {
    "ParameterKey": "PublicSubnetCidr", <11>
    "ParameterValue": "10.0.128.0/20" <12>
  }
]
----
<1> A short, representative cluster name to use for hostnames, etc.
<2> Specify the cluster name that you used when you generated the `install-config.yaml` file for the cluster.
<3> The VPC created resources will belong to.
<4> Specify the `VpcId` value from the output of the CloudFormation template
for the VPC.
<5> The Public Route Table ID for the VPC.
<6> Specify the `PublicRouteTableId` value from the output of the CloudFormation template for the VPC.
<7>  The local zone name that the VPC belongs to.
<8> Specify the local zone that you opted your AWS account into, such as `us-east-1-nyc-1a`.
<9> The shortname of the local zone that the VPC belongs to.
<10> Specify the local zone that you opted your AWS account into, such as `nyc1`.
//How do we determine this shortname?
<11> The CIDR block to allow access to the local zone.
<12> Specify a CIDR block in the format `x.x.x.x/16-24`.
//How do we know what this CIDR is?


. Copy the template from the *CloudFormation template for the VPC*
section of this topic and save it as a YAML file on your computer. This template
describes the VPC that your cluster requires.

. Launch the CloudFormation template to create a stack of AWS resources that represent the VPC:
+
[IMPORTANT]
====
You must enter the command on a single line.
====
+
[source,terminal]
----
$ aws cloudformation create-stack --stack-name <name> <1>
     --template-body file://<template>.yaml <2>
     --parameters file://<parameters>.json <3>
----
<1> `<name>` is the name for the CloudFormation stack, such as `cluster-lz-<local_zone_shortname>`.
You need the name of this stack if you remove the cluster.
<2> `<template>` is the relative path to and name of the CloudFormation template
YAML file that you saved.
<3> `<parameters>` is the relative path to and name of the CloudFormation
parameters JSON file.
+
.Example output
[source,terminal]
----
arn:aws:cloudformation:us-east-1:269333783861:stack/cluster-lz-nyc1/dbedae40-2fd3-11eb-820e-12a48460849f
----

. Confirm that the template components exist:
+
[source,terminal]
----
$ aws cloudformation describe-stacks --stack-name <name>
----
+
After the `StackStatus` displays `CREATE_COMPLETE`, the output displays values
for the following parameters. You must provide these parameter values to
the other CloudFormation templates that you run to create your cluster:
[horizontal]
`PublicSubnetIds`:: The IDs of the new public subnets.
