// Module included in the following assemblies:
//
// * installing/installing_aws/installing-aws-account.adoc

:_content-type: PROCEDURE
[id="installation-aws-add-local-zone-locations_{context}"]
= Opting in to local zone locations

If you plan to install your cluster by using Cloud Formation templates and using local zones, you must opt in to each local zone separately.

.Prerequisites

* You have installed the AWS CLI.
* You have determined into which region you will deploy your {product-title} cluster.

.Procedure

. Export a variable to contain the name of the region in which you plan to deploy your {product-title} cluster by running the following command:
+
[source,terminal]
----
$ export CLUSTER_REGION="<region_name>" <1>
----
<1> For `<region_name>`, specify a valid AWS region name, such as `us-east-1`.

. Review the list of zones that your region contains by running the following command:
+
[source,terminal]
----
$ aws ec2 describe-availability-zones \
    --filters Name=region-name,Values=${CLUSTER_REGION} \
    --query 'AvailabilityZones[].ZoneName' \
    --all-availability-zones
----
+
Depending on the region, the list of available zones can be long. Things you need to know:
+
`${REGION}[a-z]`:: Availability zones available in the region
`${REGION}-LID-N[a-z]`:: Available Local Zones. `${REGION}-LID-N` is the zone group identifier, and `[a-z]` is the zone identifier
`${REGION}-wl1-LID-wlz-[1-9]`:: Available Wavelength zones

. Export a variable to contain the name of the local zone to host your VPC by running the following command:
+
[source,terminal]
----
$ export ZONE_GROUP_NAME="${CLUSTER_REGION}-<location_identifier>-<zone_identifier>" <1>
----
<1> For `<location_identifier>-<zone_identifier>`, specify the location identifier and zone identifier for the local zone that you selected for your region. For example, specify `nyc-1a` to use the US East (New York) local zone.


. Opt in to the zone group on your AWS account by running the following command:
+
[source,terminal]
----
aws ec2 modify-availability-zone-group \
    --group-name "${ZONE_GROUP_NAME}" \
    --opt-in-status opted-in
----
